theme: jekyll-theme-minimal
title: "Marshall Allen"
description: "PhD Student, African American and African Diaspora Studies, Indiana University"
logo: /assets/img/allen-marshall.jpg
author: "Marshal Allen"
